global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nextjs'
    static_configs:
      - targets: ['nextjs:3000']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
